name: Pytest

on:
  pull_request:
  push:
    branches: main

jobs:
  conda-pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dummy-environment # name of env
          channel-priority: strict
          auto-activate-base: false
          environment-file: environment.yaml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Conda list
        shell: bash -l {0}

        run: conda list
      - name: pytest
        shell: bash -l {0}
        run: |